/*
 * QEMU Stubs for Nintendo Switch - Trace System
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

#include "qemu/osdep.h"
#include "common.h"
#include <stdint.h>
#include <sys/types.h>

/*
 * Trace system stubs
 * These are used by the QEMU tracing infrastructure
 */

/* Trace state variables for Switch builds without trace backends */
uint8_t _TRACE_FIND_RAM_OFFSET_DSTATE = 0;
uint8_t _TRACE_FIND_RAM_OFFSET_LOOP_DSTATE = 0;

uint8_t _TRACE_NV2A_DMA_MAP_DSTATE = 0;
uint8_t _TRACE_NV2A_IRQ_DSTATE = 0;
uint8_t _TRACE_NV2A_PGRAPH_FLIP_INCREMENT_WRITE_DSTATE = 0;
uint8_t _TRACE_NV2A_PGRAPH_FLIP_STALL_DSTATE = 0;
uint8_t _TRACE_NV2A_PGRAPH_METHOD_DSTATE = 0;
uint8_t _TRACE_NV2A_PGRAPH_METHOD_ABBREV_DSTATE = 0;
uint8_t _TRACE_NV2A_PGRAPH_METHOD_UNHANDLED_DSTATE = 0;
uint8_t _TRACE_NV2A_PGRAPH_SURFACE_COMPARE_MISMATCH_DSTATE = 0;
uint8_t _TRACE_NV2A_PGRAPH_SURFACE_CPU_READ_DSTATE = 0;
uint8_t _TRACE_NV2A_PGRAPH_SURFACE_CPU_WRITE_DSTATE = 0;
uint8_t _TRACE_NV2A_PGRAPH_SURFACE_CREATE_COLOR_DSTATE = 0;
uint8_t _TRACE_NV2A_PGRAPH_SURFACE_CREATE_ZETA_DSTATE = 0;
uint8_t _TRACE_NV2A_PGRAPH_SURFACE_DOWNLOAD_DSTATE = 0;
uint8_t _TRACE_NV2A_PGRAPH_SURFACE_EVICT_OVERLAPPING_DSTATE = 0;
uint8_t _TRACE_NV2A_PGRAPH_SURFACE_EVICT_REASON_DSTATE = 0;
uint8_t _TRACE_NV2A_PGRAPH_SURFACE_HIT_COLOR_DSTATE = 0;
uint8_t _TRACE_NV2A_PGRAPH_SURFACE_HIT_ZETA_DSTATE = 0;
uint8_t _TRACE_NV2A_PGRAPH_SURFACE_INVALIDATED_DSTATE = 0;
uint8_t _TRACE_NV2A_PGRAPH_SURFACE_MATCH_COLOR_DSTATE = 0;
uint8_t _TRACE_NV2A_PGRAPH_SURFACE_MATCH_ZETA_DSTATE = 0;
uint8_t _TRACE_NV2A_PGRAPH_SURFACE_MIGRATE_TYPE_DSTATE = 0;
uint8_t _TRACE_NV2A_PGRAPH_SURFACE_RENDER_TO_TEXTURE_DSTATE = 0;
uint8_t _TRACE_NV2A_PGRAPH_SURFACE_TARGET_DSTATE = 0;
uint8_t _TRACE_NV2A_PGRAPH_SURFACE_TEXTURE_COMPAT_FAILED_DSTATE = 0;
uint8_t _TRACE_NV2A_PGRAPH_SURFACE_UPLOAD_DSTATE = 0;
uint8_t _TRACE_NV2A_REG_READ_DSTATE = 0;
uint8_t _TRACE_NV2A_REG_WRITE_DSTATE = 0;

uint8_t _TRACE_PCI_ROUTE_IRQ_DSTATE = 0;
uint8_t _TRACE_PCI_UPDATE_MAPPINGS_ADD_DSTATE = 0;
uint8_t _TRACE_PCI_UPDATE_MAPPINGS_DEL_DSTATE = 0;
uint8_t _TRACE_PCI_CFG_WRITE_DSTATE = 0;
uint8_t _TRACE_PCI_CFG_READ_DSTATE = 0;
uint8_t _TRACE_CPU_RESET_DSTATE = 0;

uint8_t _TRACE_LOAD_FILE_DSTATE = 0;
uint16_t _TRACE_LOADER_WRITE_ROM_DSTATE = 0;

uint8_t _TRACE_DSP_READ_PERIPHERAL_DSTATE = 0;
uint8_t _TRACE_DSP_WRITE_PERIPHERAL_DSTATE = 0;
uint8_t _TRACE_DSP56K_EXECUTE_INSTRUCTION_DSTATE = 0;
uint8_t _TRACE_DSP56K_EXECUTE_INSTRUCTION_DISASM_DSTATE = 0;
uint8_t _TRACE_MCPX_APU_METHOD_DSTATE = 0;



uint8_t _TRACE_RUNSTATE_SET_DSTATE = 0;
uint8_t _TRACE_SYSTEM_WAKEUP_REQUEST_DSTATE = 0;
uint8_t _TRACE_VM_STATE_NOTIFY_DSTATE = 0;
uint8_t _TRACE_DISPLAYSURFACE_FREE_DSTATE = 0;
uint8_t _TRACE_DISPLAYSURFACE_CREATE_FROM_DSTATE = 0;
uint8_t _TRACE_DISPLAYSURFACE_CREATE_DSTATE = 0;
uint8_t _TRACE_DISPLAYCHANGELISTENER_REGISTER_DSTATE = 0;
uint8_t _TRACE_CONSOLE_REFRESH_DSTATE = 0;
uint8_t _TRACE_CONSOLE_GFX_REUSE_DSTATE = 0;
uint8_t _TRACE_CONSOLE_GFX_NEW_DSTATE = 0;
uint16_t _TRACE_CONSOLE_PUTCHAR_CSI_DSTATE = 0;
uint16_t _TRACE_CONSOLE_PUTCHAR_UNHANDLED_DSTATE = 0;
uint16_t _TRACE_CONSOLE_TXT_NEW_DSTATE = 0;

/* Additional trace DSTATE variables for full link */
uint8_t _TRACE_ACPI_GPE_EN_IOPORT_READB_DSTATE = 0;
uint8_t _TRACE_ACPI_GPE_EN_IOPORT_WRITEB_DSTATE = 0;
uint8_t _TRACE_ACPI_GPE_STS_IOPORT_READB_DSTATE = 0;
uint8_t _TRACE_ACPI_GPE_STS_IOPORT_WRITEB_DSTATE = 0;
uint8_t _TRACE_CLOCK_DISCONNECT_DSTATE = 0;
uint8_t _TRACE_FLATVIEW_DESTROY_DSTATE = 0;
uint8_t _TRACE_FLATVIEW_DESTROY_RCU_DSTATE = 0;
uint8_t _TRACE_FLATVIEW_NEW_DSTATE = 0;
uint8_t _TRACE_I2C_EVENT_DSTATE = 0;
uint8_t _TRACE_I2C_RECV_DSTATE = 0;
uint8_t _TRACE_I2C_SEND_DSTATE = 0;
uint8_t _TRACE_MCPX_APU_REG_READ_DSTATE = 0;
uint8_t _TRACE_MCPX_APU_REG_WRITE_DSTATE = 0;
uint8_t _TRACE_MEMORY_REGION_OPS_READ_DSTATE = 0;
uint8_t _TRACE_MEMORY_REGION_OPS_WRITE_DSTATE = 0;
uint8_t _TRACE_MEMORY_REGION_RAM_DEVICE_READ_DSTATE = 0;
uint8_t _TRACE_MEMORY_REGION_RAM_DEVICE_WRITE_DSTATE = 0;
uint8_t _TRACE_MEMORY_REGION_SUBPAGE_READ_DSTATE = 0;
uint8_t _TRACE_MEMORY_REGION_SUBPAGE_WRITE_DSTATE = 0;
uint8_t _TRACE_MEMORY_REGION_SYNC_DIRTY_DSTATE = 0;
uint8_t _TRACE_NVNET_CANT_RX_DSTATE = 0;
uint8_t _TRACE_NVNET_CANT_TX_DSTATE = 0;
uint8_t _TRACE_NVNET_DESC_STORE_DSTATE = 0;
uint8_t _TRACE_NVNET_IO_READ_DSTATE = 0;
uint8_t _TRACE_NVNET_IO_WRITE_DSTATE = 0;
uint8_t _TRACE_NVNET_LINK_NEGOTIATION_DONE_DSTATE = 0;
uint8_t _TRACE_NVNET_LINK_NEGOTIATION_START_DSTATE = 0;
uint8_t _TRACE_NVNET_LINK_STATUS_CHANGED_DSTATE = 0;
uint8_t _TRACE_NVNET_PACKET_TX_DSTATE = 0;
uint8_t _TRACE_NVNET_PHY_REG_READ_DSTATE = 0;
uint8_t _TRACE_NVNET_PHY_REG_WRITE_DSTATE = 0;
uint8_t _TRACE_NVNET_REG_READ_DSTATE = 0;
uint8_t _TRACE_NVNET_REG_WRITE_DSTATE = 0;
uint8_t _TRACE_NVNET_RX_DMA_DSTATE = 0;
uint8_t _TRACE_NVNET_RX_FILTER_BCAST_MATCH_DSTATE = 0;
uint8_t _TRACE_NVNET_RX_FILTER_DROPPED_DSTATE = 0;
uint8_t _TRACE_NVNET_RX_FILTER_MCAST_MATCH_DSTATE = 0;
uint8_t _TRACE_NVNET_RX_FILTER_MCAST_MISMATCH_DSTATE = 0;
uint8_t _TRACE_NVNET_RX_FILTER_UCAST_MATCH_DSTATE = 0;
uint8_t _TRACE_NVNET_RX_FILTER_UCAST_MISMATCH_DSTATE = 0;
uint8_t _TRACE_NVNET_RX_OVERSIZED_DSTATE = 0;
uint8_t _TRACE_NVNET_TX_DMA_DSTATE = 0;
uint8_t _TRACE_NVNET_UPDATE_IRQ_DSTATE = 0;
uint8_t _TRACE_QDEV_UPDATE_PARENT_BUS_DSTATE = 0;
uint8_t _TRACE_RESETTABLE_RESET_DSTATE = 0;
uint8_t _TRACE_RESETTABLE_CHANGE_PARENT_DSTATE = 0;
uint8_t _TRACE_RESETTABLE_PHASE_ENTER_BEGIN_DSTATE = 0;
uint8_t _TRACE_RESETTABLE_PHASE_ENTER_END_DSTATE = 0;
uint8_t _TRACE_RESETTABLE_PHASE_ENTER_EXEC_DSTATE = 0;
uint8_t _TRACE_RESETTABLE_PHASE_EXIT_BEGIN_DSTATE = 0;
uint8_t _TRACE_RESETTABLE_PHASE_EXIT_END_DSTATE = 0;
uint8_t _TRACE_RESETTABLE_PHASE_EXIT_EXEC_DSTATE = 0;
uint8_t _TRACE_RESETTABLE_PHASE_HOLD_BEGIN_DSTATE = 0;
uint8_t _TRACE_RESETTABLE_PHASE_HOLD_END_DSTATE = 0;
uint8_t _TRACE_RESETTABLE_PHASE_HOLD_EXEC_DSTATE = 0;
uint8_t _TRACE_RESETTABLE_RESET_ASSERT_BEGIN_DSTATE = 0;
uint8_t _TRACE_RESETTABLE_RESET_ASSERT_END_DSTATE = 0;
uint8_t _TRACE_RESETTABLE_RESET_RELEASE_BEGIN_DSTATE = 0;
uint8_t _TRACE_RESETTABLE_RESET_RELEASE_END_DSTATE = 0;
uint8_t _TRACE_BREAKPOINT_REMOVE_DSTATE = 0;
uint8_t _TRACE_VM_STOP_FLUSH_ALL_DSTATE = 0;
uint8_t _TRACE_AUDIO_TIMER_START_DSTATE = 0;
uint8_t _TRACE_AUDIO_TIMER_STOP_DSTATE = 0;
uint8_t _TRACE_AUDIO_TIMER_DELAYED_DSTATE = 0;
uint8_t _TRACE_VISIT_CHECK_LIST_DSTATE = 0;
uint8_t _TRACE_VISIT_CHECK_STRUCT_DSTATE = 0;
uint8_t _TRACE_VISIT_COMPLETE_DSTATE = 0;
uint8_t _TRACE_VISIT_END_ALTERNATE_DSTATE = 0;
uint8_t _TRACE_VISIT_END_LIST_DSTATE = 0;
uint8_t _TRACE_VISIT_END_STRUCT_DSTATE = 0;
uint8_t _TRACE_VISIT_FREE_DSTATE = 0;
uint8_t _TRACE_VISIT_NEXT_LIST_DSTATE = 0;
uint8_t _TRACE_VISIT_OPTIONAL_DSTATE = 0;
uint8_t _TRACE_VISIT_POLICY_REJECT_DSTATE = 0;
uint8_t _TRACE_VISIT_POLICY_SKIP_DSTATE = 0;
uint8_t _TRACE_VISIT_START_ALTERNATE_DSTATE = 0;
uint8_t _TRACE_VISIT_START_LIST_DSTATE = 0;
uint8_t _TRACE_VISIT_START_STRUCT_DSTATE = 0;
uint8_t _TRACE_VISIT_TYPE_ANY_DSTATE = 0;
uint8_t _TRACE_VISIT_TYPE_BOOL_DSTATE = 0;
uint8_t _TRACE_VISIT_TYPE_ENUM_DSTATE = 0;
uint8_t _TRACE_VISIT_TYPE_INT32_DSTATE = 0;
uint8_t _TRACE_VISIT_TYPE_INT64_DSTATE = 0;
uint8_t _TRACE_VISIT_TYPE_INT_DSTATE = 0;
uint8_t _TRACE_VISIT_TYPE_NULL_DSTATE = 0;
uint8_t _TRACE_VISIT_TYPE_NUMBER_DSTATE = 0;
uint8_t _TRACE_VISIT_TYPE_SIZE_DSTATE = 0;
uint8_t _TRACE_VISIT_TYPE_STR_DSTATE = 0;
uint8_t _TRACE_VISIT_TYPE_UINT16_DSTATE = 0;
uint8_t _TRACE_VISIT_TYPE_UINT32_DSTATE = 0;
uint8_t _TRACE_VISIT_TYPE_UINT64_DSTATE = 0;
uint8_t _TRACE_VISIT_TYPE_UINT8_DSTATE = 0;

uint8_t _TRACE_QEMU_SYSTEM_SHUTDOWN_REQUEST_DSTATE = 0;
uint8_t _TRACE_QEMU_SYSTEM_RESET_REQUEST_DSTATE = 0;
uint8_t _TRACE_OBJECT_DYNAMIC_CAST_ASSERT_DSTATE = 0;
uint8_t _TRACE_OBJECT_CLASS_DYNAMIC_CAST_ASSERT_DSTATE = 0;

/* Trace DSTATE variables for PIC (i8259) */
uint16_t _TRACE_PIC_UPDATE_IRQ_DSTATE = 0;
uint16_t _TRACE_PIC_INTERRUPT_DSTATE = 0;
uint16_t _TRACE_PIC_IOPORT_WRITE_DSTATE = 0;
uint16_t _TRACE_PIC_SET_IRQ_DSTATE = 0;
uint16_t _TRACE_PIC_IOPORT_READ_DSTATE = 0;
uint16_t _TRACE_X86_PIC_INTERRUPT_DSTATE = 0;
uint16_t _TRACE_X86_GSI_INTERRUPT_DSTATE = 0;
uint16_t _TRACE_CPU_SET_APIC_BASE_DSTATE = 0;
uint16_t _TRACE_CPU_GET_APIC_BASE_DSTATE = 0;
uint16_t _TRACE_APIC_LOCAL_DELIVER_DSTATE = 0;
uint16_t _TRACE_APIC_DELIVER_IRQ_DSTATE = 0;
uint16_t _TRACE_APIC_REGISTER_READ_DSTATE = 0;
uint16_t _TRACE_APIC_REGISTER_WRITE_DSTATE = 0;

/* Trace DSTATE for accel_tcg */
uint16_t _TRACE_STORE_ATOM16_FALLBACK_DSTATE = 0;
uint16_t _TRACE_MEMORY_NOTDIRTY_SET_DIRTY_DSTATE = 0;
uint16_t _TRACE_MEMORY_NOTDIRTY_WRITE_ACCESS_DSTATE = 0;
uint16_t _TRACE_TRANSLATE_BLOCK_DSTATE = 0;
uint16_t _TRACE_EXEC_TB_DSTATE = 0;
uint16_t _TRACE_EXEC_TB_EXIT_DSTATE = 0;
uint16_t _TRACE_BREAKPOINT_INSERT_DSTATE = 0;
uint16_t _TRACE_BREAKPOINT_SINGLESTEP_DSTATE = 0;
uint16_t _TRACE_I8257_UNREGISTERED_DMA_DSTATE = 0;

/* IDE trace DSTATE variables */
uint16_t _TRACE_BMDMA_ADDR_WRITE_DSTATE = 0;
uint16_t _TRACE_BMDMA_ADDR_READ_DSTATE = 0;
uint16_t _TRACE_BMDMA_RESET_DSTATE = 0;
uint16_t _TRACE_BMDMA_READ_DSTATE = 0;
uint16_t _TRACE_BMDMA_WRITE_DSTATE = 0;
uint16_t _TRACE_CD_READ_SECTOR_SYNC_DSTATE = 0;
uint16_t _TRACE_CD_READ_SECTOR_CB_DSTATE = 0;
uint16_t _TRACE_CD_READ_SECTOR_DSTATE = 0;
uint16_t _TRACE_IDE_ATAPI_CMD_REPLY_END_EOT_DSTATE = 0;
uint16_t _TRACE_IDE_ATAPI_CMD_REPLY_END_BCL_DSTATE = 0;
uint16_t _TRACE_IDE_ATAPI_CMD_REPLY_END_NEW_DSTATE = 0;
uint16_t _TRACE_IDE_ATAPI_CMD_CHECK_STATUS_DSTATE = 0;
uint16_t _TRACE_IDE_ATAPI_CMD_READ_DSTATE = 0;
uint16_t _TRACE_IDE_ATAPI_CMD_DSTATE = 0;
uint16_t _TRACE_IDE_ATAPI_CMD_PACKET_DSTATE = 0;
uint16_t _TRACE_DMA_BLK_IO_DSTATE = 0;
uint16_t _TRACE_DMA_AIO_CANCEL_DSTATE = 0;
uint16_t _TRACE_DMA_COMPLETE_DSTATE = 0;
uint16_t _TRACE_DMA_BLK_CB_DSTATE = 0;
uint16_t _TRACE_DMA_MAP_WAIT_DSTATE = 0;
uint16_t _TRACE_ADDRESS_SPACE_MAP_DSTATE = 0;
uint16_t _TRACE_IDE_BUS_EXEC_CMD_DSTATE = 0;
uint16_t _TRACE_IDE_IOPORT_WRITE_DSTATE = 0;
uint16_t _TRACE_IDE_BUS_RESET_AIO_DSTATE = 0;
uint16_t _TRACE_IDE_ATAPI_CMD_READ_DMA_CB_AIO_DSTATE = 0;
uint16_t _TRACE_IDE_ATAPI_CMD_ERROR_DSTATE = 0;
uint16_t _TRACE_IDE_ATAPI_CMD_REPLY_END_DSTATE = 0;
uint16_t _TRACE_IDE_DMA_CB_DSTATE = 0;
uint16_t _TRACE_IDE_CANCEL_DMA_SYNC_REMAINING_DSTATE = 0;
uint16_t _TRACE_IDE_CANCEL_DMA_SYNC_BUFFERED_DSTATE = 0;
uint16_t _TRACE_IDE_SECTOR_READ_DSTATE = 0;
uint16_t _TRACE_IDE_IOPORT_READ_DSTATE = 0;
uint16_t _TRACE_IDE_SECTOR_WRITE_DSTATE = 0;
uint16_t _TRACE_IDE_DATA_READW_DSTATE = 0;
uint16_t _TRACE_IDE_DATA_WRITEL_DSTATE = 0;
uint16_t _TRACE_IDE_DATA_WRITEW_DSTATE = 0;
uint16_t _TRACE_IDE_DATA_READL_DSTATE = 0;
uint16_t _TRACE_IDE_RESET_DSTATE = 0;
uint16_t _TRACE_IDE_STATUS_READ_DSTATE = 0;
uint16_t _TRACE_IDE_CTRL_WRITE_DSTATE = 0;
uint16_t _TRACE_BMDMA_CMD_WRITEB_DSTATE = 0;

/* HD Geometry */
uint16_t _TRACE_HD_GEOMETRY_LCHS_GUESS_DSTATE = 0;
uint16_t _TRACE_HD_GEOMETRY_GUESS_DSTATE = 0;

/* VGA trace DSTATEs used by hw/display/vga.c */
uint16_t _TRACE_VGA_STD_READ_IO_DSTATE = 0;
uint16_t _TRACE_VGA_STD_WRITE_IO_DSTATE = 0;
uint16_t _TRACE_VGA_VBE_READ_DSTATE = 0;
uint16_t _TRACE_VGA_VBE_WRITE_DSTATE = 0;

uint16_t _TRACE_KVM_REPORT_IRQ_DELIVERED_DSTATE = 0;
uint16_t _TRACE_KVM_RESET_IRQ_DELIVERED_DSTATE = 0;
uint16_t _TRACE_KVM_GET_IRQ_DELIVERED_DSTATE = 0;
uint16_t _TRACE_IOAPIC_MEM_READ_DSTATE = 0;
uint16_t _TRACE_IOAPIC_SET_REMOTE_IRR_DSTATE = 0;
uint16_t _TRACE_IOAPIC_SET_IRQ_DSTATE = 0;
uint16_t _TRACE_IOAPIC_EOI_DELAYED_REASSERT_DSTATE = 0;
uint16_t _TRACE_IOAPIC_CLEAR_REMOTE_IRR_DSTATE = 0;
uint16_t _TRACE_IOAPIC_EOI_BROADCAST_DSTATE = 0;
uint16_t _TRACE_IOAPIC_MEM_WRITE_DSTATE = 0;

uint16_t _TRACE_SERIAL_UPDATE_PARAMETERS_DSTATE = 0;
uint16_t _TRACE_SERIAL_WRITE_DSTATE = 0;
uint16_t _TRACE_SERIAL_READ_DSTATE = 0;


/* Trace functions */
int __attribute__((weak)) trace_events_enabled_count(void)
{
    return 0;
}

void __attribute__((weak)) trace_event_register_group(void *group)
{
    (void)group;
}
void __attribute__((weak)) trace_event_set_state_dynamic(void *ev, bool state)
{
    (void)ev; (void)state;
}
