/*
 * QEMU Stubs for Nintendo Switch - Trace System
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

#include "qemu/osdep.h"
#include "common.h"
#include <stdint.h>
#include <sys/types.h>

/*
 * Trace system stubs
 * These are used by the QEMU tracing infrastructure
 */

/* Trace state variables for Switch builds without trace backends */
uint8_t _TRACE_FIND_RAM_OFFSET_DSTATE = 0;
uint8_t _TRACE_FIND_RAM_OFFSET_LOOP_DSTATE = 0;

uint8_t _TRACE_NV2A_DMA_MAP_DSTATE = 0;
uint8_t _TRACE_NV2A_IRQ_DSTATE = 0;
uint8_t _TRACE_NV2A_PGRAPH_FLIP_INCREMENT_WRITE_DSTATE = 0;
uint8_t _TRACE_NV2A_PGRAPH_FLIP_STALL_DSTATE = 0;
uint8_t _TRACE_NV2A_PGRAPH_METHOD_DSTATE = 0;
uint8_t _TRACE_NV2A_PGRAPH_METHOD_ABBREV_DSTATE = 0;
uint8_t _TRACE_NV2A_PGRAPH_METHOD_UNHANDLED_DSTATE = 0;
uint8_t _TRACE_NV2A_PGRAPH_SURFACE_COMPARE_MISMATCH_DSTATE = 0;
uint8_t _TRACE_NV2A_PGRAPH_SURFACE_CPU_READ_DSTATE = 0;
uint8_t _TRACE_NV2A_PGRAPH_SURFACE_CPU_WRITE_DSTATE = 0;
uint8_t _TRACE_NV2A_PGRAPH_SURFACE_CREATE_COLOR_DSTATE = 0;
uint8_t _TRACE_NV2A_PGRAPH_SURFACE_CREATE_ZETA_DSTATE = 0;
uint8_t _TRACE_NV2A_PGRAPH_SURFACE_DOWNLOAD_DSTATE = 0;
uint8_t _TRACE_NV2A_PGRAPH_SURFACE_EVICT_OVERLAPPING_DSTATE = 0;
uint8_t _TRACE_NV2A_PGRAPH_SURFACE_EVICT_REASON_DSTATE = 0;
uint8_t _TRACE_NV2A_PGRAPH_SURFACE_HIT_COLOR_DSTATE = 0;
uint8_t _TRACE_NV2A_PGRAPH_SURFACE_HIT_ZETA_DSTATE = 0;
uint8_t _TRACE_NV2A_PGRAPH_SURFACE_INVALIDATED_DSTATE = 0;
uint8_t _TRACE_NV2A_PGRAPH_SURFACE_MATCH_COLOR_DSTATE = 0;
uint8_t _TRACE_NV2A_PGRAPH_SURFACE_MATCH_ZETA_DSTATE = 0;
uint8_t _TRACE_NV2A_PGRAPH_SURFACE_MIGRATE_TYPE_DSTATE = 0;
uint8_t _TRACE_NV2A_PGRAPH_SURFACE_RENDER_TO_TEXTURE_DSTATE = 0;
uint8_t _TRACE_NV2A_PGRAPH_SURFACE_TARGET_DSTATE = 0;
uint8_t _TRACE_NV2A_PGRAPH_SURFACE_TEXTURE_COMPAT_FAILED_DSTATE = 0;
uint8_t _TRACE_NV2A_PGRAPH_SURFACE_UPLOAD_DSTATE = 0;
uint8_t _TRACE_NV2A_REG_READ_DSTATE = 0;
uint8_t _TRACE_NV2A_REG_WRITE_DSTATE = 0;

uint8_t _TRACE_PCI_ROUTE_IRQ_DSTATE = 0;
uint8_t _TRACE_PCI_UPDATE_MAPPINGS_ADD_DSTATE = 0;
uint8_t _TRACE_PCI_UPDATE_MAPPINGS_DEL_DSTATE = 0;
uint8_t _TRACE_PCI_CFG_WRITE_DSTATE = 0;
uint8_t _TRACE_PCI_CFG_READ_DSTATE = 0;
uint8_t _TRACE_CPU_RESET_DSTATE = 0;

uint8_t _TRACE_LOAD_FILE_DSTATE = 0;
uint16_t _TRACE_LOADER_WRITE_ROM_DSTATE = 0;

uint8_t _TRACE_DSP_READ_PERIPHERAL_DSTATE = 0;
uint8_t _TRACE_DSP_WRITE_PERIPHERAL_DSTATE = 0;
uint8_t _TRACE_DSP56K_EXECUTE_INSTRUCTION_DSTATE = 0;
uint8_t _TRACE_DSP56K_EXECUTE_INSTRUCTION_DISASM_DSTATE = 0;
uint8_t _TRACE_MCPX_APU_METHOD_DSTATE = 0;



uint8_t _TRACE_RUNSTATE_SET_DSTATE = 0;
uint8_t _TRACE_SYSTEM_WAKEUP_REQUEST_DSTATE = 0;
uint8_t _TRACE_VM_STATE_NOTIFY_DSTATE = 0;
uint8_t _TRACE_DISPLAYSURFACE_FREE_DSTATE = 0;
uint8_t _TRACE_DISPLAYSURFACE_CREATE_FROM_DSTATE = 0;
uint8_t _TRACE_DISPLAYSURFACE_CREATE_DSTATE = 0;
uint8_t _TRACE_DISPLAYCHANGELISTENER_REGISTER_DSTATE = 0;
uint8_t _TRACE_CONSOLE_REFRESH_DSTATE = 0;
uint8_t _TRACE_CONSOLE_GFX_REUSE_DSTATE = 0;
uint8_t _TRACE_CONSOLE_GFX_NEW_DSTATE = 0;
uint16_t _TRACE_CONSOLE_PUTCHAR_CSI_DSTATE = 0;
uint16_t _TRACE_CONSOLE_PUTCHAR_UNHANDLED_DSTATE = 0;
uint16_t _TRACE_CONSOLE_TXT_NEW_DSTATE = 0;

/* Additional trace DSTATE variables for full link */
uint8_t _TRACE_ACPI_GPE_EN_IOPORT_READB_DSTATE = 0;
uint8_t _TRACE_ACPI_GPE_EN_IOPORT_WRITEB_DSTATE = 0;
uint8_t _TRACE_ACPI_GPE_STS_IOPORT_READB_DSTATE = 0;
uint8_t _TRACE_ACPI_GPE_STS_IOPORT_WRITEB_DSTATE = 0;
uint8_t _TRACE_CLOCK_DISCONNECT_DSTATE = 0;
uint8_t _TRACE_FLATVIEW_DESTROY_DSTATE = 0;
uint8_t _TRACE_FLATVIEW_DESTROY_RCU_DSTATE = 0;
uint8_t _TRACE_FLATVIEW_NEW_DSTATE = 0;
uint8_t _TRACE_I2C_EVENT_DSTATE = 0;
uint8_t _TRACE_I2C_RECV_DSTATE = 0;
uint8_t _TRACE_I2C_SEND_DSTATE = 0;
uint8_t _TRACE_MCPX_APU_REG_READ_DSTATE = 0;
uint8_t _TRACE_MCPX_APU_REG_WRITE_DSTATE = 0;
uint8_t _TRACE_MEMORY_REGION_OPS_READ_DSTATE = 0;
uint8_t _TRACE_MEMORY_REGION_OPS_WRITE_DSTATE = 0;
uint8_t _TRACE_MEMORY_REGION_RAM_DEVICE_READ_DSTATE = 0;
uint8_t _TRACE_MEMORY_REGION_RAM_DEVICE_WRITE_DSTATE = 0;
uint8_t _TRACE_MEMORY_REGION_SUBPAGE_READ_DSTATE = 0;
uint8_t _TRACE_MEMORY_REGION_SUBPAGE_WRITE_DSTATE = 0;
uint8_t _TRACE_MEMORY_REGION_SYNC_DIRTY_DSTATE = 0;
uint8_t _TRACE_NVNET_CANT_RX_DSTATE = 0;
uint8_t _TRACE_NVNET_CANT_TX_DSTATE = 0;
uint8_t _TRACE_NVNET_DESC_STORE_DSTATE = 0;
uint8_t _TRACE_NVNET_IO_READ_DSTATE = 0;
uint8_t _TRACE_NVNET_IO_WRITE_DSTATE = 0;
uint8_t _TRACE_NVNET_LINK_NEGOTIATION_DONE_DSTATE = 0;
uint8_t _TRACE_NVNET_LINK_NEGOTIATION_START_DSTATE = 0;
uint8_t _TRACE_NVNET_LINK_STATUS_CHANGED_DSTATE = 0;
uint8_t _TRACE_NVNET_PACKET_TX_DSTATE = 0;
uint8_t _TRACE_NVNET_PHY_REG_READ_DSTATE = 0;
uint8_t _TRACE_NVNET_PHY_REG_WRITE_DSTATE = 0;
uint8_t _TRACE_NVNET_REG_READ_DSTATE = 0;
uint8_t _TRACE_NVNET_REG_WRITE_DSTATE = 0;
uint8_t _TRACE_NVNET_RX_DMA_DSTATE = 0;
uint8_t _TRACE_NVNET_RX_FILTER_BCAST_MATCH_DSTATE = 0;
uint8_t _TRACE_NVNET_RX_FILTER_DROPPED_DSTATE = 0;
uint8_t _TRACE_NVNET_RX_FILTER_MCAST_MATCH_DSTATE = 0;
uint8_t _TRACE_NVNET_RX_FILTER_MCAST_MISMATCH_DSTATE = 0;
uint8_t _TRACE_NVNET_RX_FILTER_UCAST_MATCH_DSTATE = 0;
uint8_t _TRACE_NVNET_RX_FILTER_UCAST_MISMATCH_DSTATE = 0;
uint8_t _TRACE_NVNET_RX_OVERSIZED_DSTATE = 0;
uint8_t _TRACE_NVNET_TX_DMA_DSTATE = 0;
uint8_t _TRACE_NVNET_UPDATE_IRQ_DSTATE = 0;
uint8_t _TRACE_QDEV_UPDATE_PARENT_BUS_DSTATE = 0;
uint8_t _TRACE_RESETTABLE_RESET_DSTATE = 0;
uint8_t _TRACE_RESETTABLE_CHANGE_PARENT_DSTATE = 0;
uint8_t _TRACE_RESETTABLE_PHASE_ENTER_BEGIN_DSTATE = 0;
uint8_t _TRACE_RESETTABLE_PHASE_ENTER_END_DSTATE = 0;
uint8_t _TRACE_RESETTABLE_PHASE_ENTER_EXEC_DSTATE = 0;
uint8_t _TRACE_RESETTABLE_PHASE_EXIT_BEGIN_DSTATE = 0;
uint8_t _TRACE_RESETTABLE_PHASE_EXIT_END_DSTATE = 0;
uint8_t _TRACE_RESETTABLE_PHASE_EXIT_EXEC_DSTATE = 0;
uint8_t _TRACE_RESETTABLE_PHASE_HOLD_BEGIN_DSTATE = 0;
uint8_t _TRACE_RESETTABLE_PHASE_HOLD_END_DSTATE = 0;
uint8_t _TRACE_RESETTABLE_PHASE_HOLD_EXEC_DSTATE = 0;
uint8_t _TRACE_RESETTABLE_RESET_ASSERT_BEGIN_DSTATE = 0;
uint8_t _TRACE_RESETTABLE_RESET_ASSERT_END_DSTATE = 0;
uint8_t _TRACE_RESETTABLE_RESET_RELEASE_BEGIN_DSTATE = 0;
uint8_t _TRACE_RESETTABLE_RESET_RELEASE_END_DSTATE = 0;
uint8_t _TRACE_BREAKPOINT_REMOVE_DSTATE = 0;
uint8_t _TRACE_VM_STOP_FLUSH_ALL_DSTATE = 0;
uint8_t _TRACE_AUDIO_TIMER_START_DSTATE = 0;
uint8_t _TRACE_AUDIO_TIMER_STOP_DSTATE = 0;
uint8_t _TRACE_AUDIO_TIMER_DELAYED_DSTATE = 0;
uint8_t _TRACE_VISIT_CHECK_LIST_DSTATE = 0;
uint8_t _TRACE_VISIT_CHECK_STRUCT_DSTATE = 0;
uint8_t _TRACE_VISIT_COMPLETE_DSTATE = 0;
uint8_t _TRACE_VISIT_END_ALTERNATE_DSTATE = 0;
uint8_t _TRACE_VISIT_END_LIST_DSTATE = 0;
uint8_t _TRACE_VISIT_END_STRUCT_DSTATE = 0;
uint8_t _TRACE_VISIT_FREE_DSTATE = 0;
uint8_t _TRACE_VISIT_NEXT_LIST_DSTATE = 0;
uint8_t _TRACE_VISIT_OPTIONAL_DSTATE = 0;
uint8_t _TRACE_VISIT_POLICY_REJECT_DSTATE = 0;
uint8_t _TRACE_VISIT_POLICY_SKIP_DSTATE = 0;
uint8_t _TRACE_VISIT_START_ALTERNATE_DSTATE = 0;
uint8_t _TRACE_VISIT_START_LIST_DSTATE = 0;
uint8_t _TRACE_VISIT_START_STRUCT_DSTATE = 0;
uint8_t _TRACE_VISIT_TYPE_ANY_DSTATE = 0;
uint8_t _TRACE_VISIT_TYPE_BOOL_DSTATE = 0;
uint8_t _TRACE_VISIT_TYPE_ENUM_DSTATE = 0;
uint8_t _TRACE_VISIT_TYPE_INT32_DSTATE = 0;
uint8_t _TRACE_VISIT_TYPE_INT64_DSTATE = 0;
uint8_t _TRACE_VISIT_TYPE_INT_DSTATE = 0;
uint8_t _TRACE_VISIT_TYPE_NULL_DSTATE = 0;
uint8_t _TRACE_VISIT_TYPE_NUMBER_DSTATE = 0;
uint8_t _TRACE_VISIT_TYPE_SIZE_DSTATE = 0;
uint8_t _TRACE_VISIT_TYPE_STR_DSTATE = 0;
uint8_t _TRACE_VISIT_TYPE_UINT16_DSTATE = 0;
uint8_t _TRACE_VISIT_TYPE_UINT32_DSTATE = 0;
uint8_t _TRACE_VISIT_TYPE_UINT64_DSTATE = 0;
uint8_t _TRACE_VISIT_TYPE_UINT8_DSTATE = 0;

uint8_t _TRACE_QEMU_SYSTEM_SHUTDOWN_REQUEST_DSTATE = 0;
uint8_t _TRACE_QEMU_SYSTEM_RESET_REQUEST_DSTATE = 0;
uint8_t _TRACE_OBJECT_DYNAMIC_CAST_ASSERT_DSTATE = 0;
uint8_t _TRACE_OBJECT_CLASS_DYNAMIC_CAST_ASSERT_DSTATE = 0;

/* Trace DSTATE variables for PIC (i8259) */
uint16_t _TRACE_PIC_UPDATE_IRQ_DSTATE = 0;
uint16_t _TRACE_PIC_INTERRUPT_DSTATE = 0;
uint16_t _TRACE_PIC_IOPORT_WRITE_DSTATE = 0;
uint16_t _TRACE_PIC_SET_IRQ_DSTATE = 0;
uint16_t _TRACE_PIC_IOPORT_READ_DSTATE = 0;
uint16_t _TRACE_X86_PIC_INTERRUPT_DSTATE = 0;
uint16_t _TRACE_X86_GSI_INTERRUPT_DSTATE = 0;
uint16_t _TRACE_CPU_SET_APIC_BASE_DSTATE = 0;
uint16_t _TRACE_CPU_GET_APIC_BASE_DSTATE = 0;
uint16_t _TRACE_APIC_LOCAL_DELIVER_DSTATE = 0;
uint16_t _TRACE_APIC_DELIVER_IRQ_DSTATE = 0;
uint16_t _TRACE_APIC_REGISTER_READ_DSTATE = 0;
uint16_t _TRACE_APIC_REGISTER_WRITE_DSTATE = 0;

/* Trace DSTATE for accel_tcg */
uint16_t _TRACE_STORE_ATOM16_FALLBACK_DSTATE = 0;
uint16_t _TRACE_MEMORY_NOTDIRTY_SET_DIRTY_DSTATE = 0;
uint16_t _TRACE_MEMORY_NOTDIRTY_WRITE_ACCESS_DSTATE = 0;
uint16_t _TRACE_TRANSLATE_BLOCK_DSTATE = 0;
uint16_t _TRACE_EXEC_TB_DSTATE = 0;
uint16_t _TRACE_EXEC_TB_EXIT_DSTATE = 0;
uint16_t _TRACE_BREAKPOINT_INSERT_DSTATE = 0;
uint16_t _TRACE_BREAKPOINT_SINGLESTEP_DSTATE = 0;
uint16_t _TRACE_I8257_UNREGISTERED_DMA_DSTATE = 0;

/* IDE trace DSTATE variables */
uint16_t _TRACE_BMDMA_ADDR_WRITE_DSTATE = 0;
uint16_t _TRACE_BMDMA_ADDR_READ_DSTATE = 0;
uint16_t _TRACE_BMDMA_RESET_DSTATE = 0;
uint16_t _TRACE_BMDMA_READ_DSTATE = 0;
uint16_t _TRACE_BMDMA_WRITE_DSTATE = 0;
uint16_t _TRACE_CD_READ_SECTOR_SYNC_DSTATE = 0;
uint16_t _TRACE_CD_READ_SECTOR_CB_DSTATE = 0;
uint16_t _TRACE_CD_READ_SECTOR_DSTATE = 0;
uint16_t _TRACE_IDE_ATAPI_CMD_REPLY_END_EOT_DSTATE = 0;
uint16_t _TRACE_IDE_ATAPI_CMD_REPLY_END_BCL_DSTATE = 0;
uint16_t _TRACE_IDE_ATAPI_CMD_REPLY_END_NEW_DSTATE = 0;
uint16_t _TRACE_IDE_ATAPI_CMD_CHECK_STATUS_DSTATE = 0;
uint16_t _TRACE_IDE_ATAPI_CMD_READ_DSTATE = 0;
uint16_t _TRACE_IDE_ATAPI_CMD_DSTATE = 0;
uint16_t _TRACE_IDE_ATAPI_CMD_PACKET_DSTATE = 0;
uint16_t _TRACE_DMA_BLK_IO_DSTATE = 0;
uint16_t _TRACE_DMA_AIO_CANCEL_DSTATE = 0;
uint16_t _TRACE_DMA_COMPLETE_DSTATE = 0;
uint16_t _TRACE_DMA_BLK_CB_DSTATE = 0;
uint16_t _TRACE_DMA_MAP_WAIT_DSTATE = 0;
uint16_t _TRACE_ADDRESS_SPACE_MAP_DSTATE = 0;
uint16_t _TRACE_IDE_BUS_EXEC_CMD_DSTATE = 0;
uint16_t _TRACE_IDE_IOPORT_WRITE_DSTATE = 0;
uint16_t _TRACE_IDE_BUS_RESET_AIO_DSTATE = 0;
uint16_t _TRACE_IDE_ATAPI_CMD_READ_DMA_CB_AIO_DSTATE = 0;
uint16_t _TRACE_IDE_ATAPI_CMD_ERROR_DSTATE = 0;
uint16_t _TRACE_IDE_ATAPI_CMD_REPLY_END_DSTATE = 0;
uint16_t _TRACE_IDE_DMA_CB_DSTATE = 0;
uint16_t _TRACE_IDE_CANCEL_DMA_SYNC_REMAINING_DSTATE = 0;
uint16_t _TRACE_IDE_CANCEL_DMA_SYNC_BUFFERED_DSTATE = 0;
uint16_t _TRACE_IDE_SECTOR_READ_DSTATE = 0;
uint16_t _TRACE_IDE_IOPORT_READ_DSTATE = 0;
uint16_t _TRACE_IDE_SECTOR_WRITE_DSTATE = 0;
uint16_t _TRACE_IDE_DATA_READW_DSTATE = 0;
uint16_t _TRACE_IDE_DATA_WRITEL_DSTATE = 0;
uint16_t _TRACE_IDE_DATA_WRITEW_DSTATE = 0;
uint16_t _TRACE_IDE_DATA_READL_DSTATE = 0;
uint16_t _TRACE_IDE_RESET_DSTATE = 0;
uint16_t _TRACE_IDE_STATUS_READ_DSTATE = 0;
uint16_t _TRACE_IDE_CTRL_WRITE_DSTATE = 0;
uint16_t _TRACE_BMDMA_CMD_WRITEB_DSTATE = 0;

/* HD Geometry */
uint16_t _TRACE_HD_GEOMETRY_LCHS_GUESS_DSTATE = 0;
uint16_t _TRACE_HD_GEOMETRY_GUESS_DSTATE = 0;

/* VGA trace DSTATEs used by hw/display/vga.c */
uint16_t _TRACE_VGA_STD_READ_IO_DSTATE = 0;
uint16_t _TRACE_VGA_STD_WRITE_IO_DSTATE = 0;
uint16_t _TRACE_VGA_VBE_READ_DSTATE = 0;
uint16_t _TRACE_VGA_VBE_WRITE_DSTATE = 0;

uint16_t _TRACE_KVM_REPORT_IRQ_DELIVERED_DSTATE = 0;
uint16_t _TRACE_KVM_RESET_IRQ_DELIVERED_DSTATE = 0;
uint16_t _TRACE_KVM_GET_IRQ_DELIVERED_DSTATE = 0;
uint16_t _TRACE_IOAPIC_MEM_READ_DSTATE = 0;
uint16_t _TRACE_IOAPIC_SET_REMOTE_IRR_DSTATE = 0;
uint16_t _TRACE_IOAPIC_SET_IRQ_DSTATE = 0;
uint16_t _TRACE_IOAPIC_EOI_DELAYED_REASSERT_DSTATE = 0;
uint16_t _TRACE_IOAPIC_CLEAR_REMOTE_IRR_DSTATE = 0;
uint16_t _TRACE_IOAPIC_EOI_BROADCAST_DSTATE = 0;
uint16_t _TRACE_IOAPIC_MEM_WRITE_DSTATE = 0;

uint16_t _TRACE_SERIAL_UPDATE_PARAMETERS_DSTATE = 0;
uint16_t _TRACE_SERIAL_WRITE_DSTATE = 0;
uint16_t _TRACE_SERIAL_READ_DSTATE = 0;

uint16_t _TRACE_MIGRATE_FD_CANCEL_DSTATE = 0;
uint16_t _TRACE_MIGRATE_SET_STATE_DSTATE = 0;
uint16_t _TRACE_DIRTY_BITMAP_LOAD_BITS_ENTER_DSTATE = 0;
uint16_t _TRACE_DIRTY_BITMAP_LOAD_HEADER_DSTATE = 0;
uint16_t _TRACE_DIRTY_BITMAP_LOAD_COMPLETE_DSTATE = 0;
uint16_t _TRACE_DIRTY_BITMAP_SAVE_COMPLETE_ENTER_DSTATE = 0;
uint16_t _TRACE_DIRTY_BITMAP_SAVE_COMPLETE_FINISH_DSTATE = 0;
uint16_t _TRACE_RAM_SAVE_PAGE_DSTATE = 0;
uint16_t _TRACE_SAVE_XBZRLE_PAGE_SKIPPING_DSTATE = 0;
uint16_t _TRACE_SAVE_XBZRLE_PAGE_OVERFLOW_DSTATE = 0;
uint16_t _TRACE_RAM_BLOCK_DISCARD_RANGE_DSTATE = 0;
uint16_t _TRACE_RAM_LOAD_START_DSTATE = 0;
uint16_t _TRACE_RAM_LOAD_COMPLETE_DSTATE = 0;
uint16_t _TRACE_RAM_LOAD_LOOP_DSTATE = 0;
uint16_t _TRACE_RAM_LOAD_POSTCOPY_LOOP_DSTATE = 0;
uint16_t _TRACE_MIGRATION_TRANSFERRED_BYTES_DSTATE = 0;
uint16_t _TRACE_RAM_DISCARD_RANGE_DSTATE = 0;
uint16_t _TRACE_RAM_SAVE_ITERATE_BIG_WAIT_DSTATE = 0;
uint16_t _TRACE_MIGRATION_THROTTLE_DSTATE = 0;
uint16_t _TRACE_MIGRATION_DIRTY_LIMIT_GUEST_DSTATE = 0;
uint16_t _TRACE_MIGRATION_BITMAP_SYNC_END_DSTATE = 0;
uint16_t _TRACE_MIGRATION_BITMAP_SYNC_START_DSTATE = 0;
uint16_t _TRACE_GET_QUEUED_PAGE_NOT_DIRTY_DSTATE = 0;
uint16_t _TRACE_GET_QUEUED_PAGE_DSTATE = 0;
uint16_t _TRACE_RAM_STATE_RESUME_PREPARE_DSTATE = 0;
uint16_t _TRACE_RAM_DIRTY_BITMAP_SYNC_START_DSTATE = 0;
uint16_t _TRACE_RAM_DIRTY_BITMAP_SYNC_WAIT_DSTATE = 0;
uint16_t _TRACE_RAM_DIRTY_BITMAP_SYNC_COMPLETE_DSTATE = 0;
uint16_t _TRACE_RAM_DIRTY_BITMAP_REQUEST_DSTATE = 0;
uint16_t _TRACE_MIGRATION_BITMAP_CLEAR_DIRTY_DSTATE = 0;
uint16_t _TRACE_MIGRATION_PAGECACHE_INIT_DSTATE = 0;
uint16_t _TRACE_MIGRATION_PAGECACHE_INSERT_DSTATE = 0;
uint16_t _TRACE_MULTIFD_SEND_FILL_DSTATE = 0;
uint16_t _TRACE_MULTIFD_SEND_SYNC_MAIN_SIGNAL_DSTATE = 0;
uint16_t _TRACE_MULTIFD_SEND_SYNC_MAIN_WAIT_DSTATE = 0;
uint16_t _TRACE_MULTIFD_SEND_SYNC_MAIN_DSTATE = 0;
uint16_t _TRACE_MULTIFD_RECV_SYNC_MAIN_SIGNAL_DSTATE = 0;
uint16_t _TRACE_MULTIFD_RECV_SYNC_MAIN_WAIT_DSTATE = 0;
uint16_t _TRACE_MULTIFD_RECV_SYNC_MAIN_DSTATE = 0;
uint16_t _TRACE_DIRTY_BITMAP_SAVE_ITERATE_DSTATE = 0;
uint16_t _TRACE_DIRTY_BITMAP_LOAD_BITS_ZEROES_DSTATE = 0;
uint16_t _TRACE_DIRTY_BITMAP_LOAD_ENTER_DSTATE = 0;
uint16_t _TRACE_DIRTY_BITMAP_LOAD_SUCCESS_DSTATE = 0;
uint16_t _TRACE_SEND_BITMAP_BITS_DSTATE = 0;
uint16_t _TRACE_DIRTY_BITMAP_STATE_PENDING_DSTATE = 0;
uint16_t _TRACE_SEND_BITMAP_HEADER_ENTER_DSTATE = 0;
uint16_t _TRACE_GLOBAL_DIRTY_CHANGED_DSTATE = 0;
uint16_t _TRACE_MULTIFD_SEND_RAM_FILL_DSTATE = 0;
uint16_t _TRACE_MIGRATE_TRANSFERRED_DSTATE = 0;
uint16_t _TRACE_MIGRATE_ERROR_DSTATE = 0;
uint16_t _TRACE_SAVEVM_SECTION_START_DSTATE = 0;
uint16_t _TRACE_VMSTATE_DOWNTIME_SAVE_DSTATE = 0;
uint16_t _TRACE_VMSTATE_DOWNTIME_CHECKPOINT_DSTATE = 0;
uint16_t _TRACE_SAVEVM_STATE_COMPLETE_PRECOPY_DSTATE = 0;
uint16_t _TRACE_SAVEVM_SECTION_END_DSTATE = 0;
uint16_t _TRACE_SAVEVM_STATE_CLEANUP_DSTATE = 0;
uint16_t _TRACE_SAVEVM_STATE_HEADER_DSTATE = 0;
uint16_t _TRACE_SAVEVM_STATE_SETUP_DSTATE = 0;
uint16_t _TRACE_SAVEVM_STATE_ITERATE_DSTATE = 0;
uint16_t _TRACE_SAVEVM_SEND_RECV_BITMAP_DSTATE = 0;
uint16_t _TRACE_VMSTATE_SAVE_DSTATE = 0;
uint16_t _TRACE_SAVEVM_SECTION_SKIP_DSTATE = 0;
uint16_t _TRACE_SAVEVM_COMMAND_SEND_DSTATE = 0;
uint16_t _TRACE_QEMU_FILE_FCLOSE_DSTATE = 0;
uint16_t _TRACE_JOB_COMPLETED_DSTATE = 0;
uint16_t _TRACE_MIGRATION_FILE_INCOMING_DSTATE = 0;
uint16_t _TRACE_INPUT_EVENT_KEY_NUMBER_DSTATE = 0;
uint16_t _TRACE_INPUT_EVENT_MTT_DSTATE = 0;
uint16_t _TRACE_INPUT_EVENT_SYNC_DSTATE = 0;
uint16_t _TRACE_INPUT_EVENT_ABS_DSTATE = 0;
uint16_t _TRACE_INPUT_EVENT_REL_DSTATE = 0;
uint16_t _TRACE_INPUT_EVENT_KEY_QCODE_DSTATE = 0;
uint16_t _TRACE_INPUT_EVENT_BTN_DSTATE = 0;
uint16_t _TRACE_CPU_THROTTLE_DIRTY_SYNC_DSTATE = 0;
uint16_t _TRACE_CPU_THROTTLE_SET_DSTATE = 0;
uint16_t _TRACE_VMSTATE_SUBSECTION_SAVE_TOP_DSTATE = 0;
uint16_t _TRACE_VMSTATE_SAVE_STATE_TOP_DSTATE = 0;
uint16_t _TRACE_VMSTATE_SUBSECTION_SAVE_LOOP_DSTATE = 0;
uint16_t _TRACE_VMSTATE_SAVE_STATE_PRE_SAVE_RES_DSTATE = 0;
uint16_t _TRACE_VMSTATE_SAVE_STATE_LOOP_DSTATE = 0;
uint16_t _TRACE_VMSTATE_N_ELEMS_DSTATE = 0;
uint16_t _TRACE_VMSTATE_FIELD_EXISTS_DSTATE = 0;
uint16_t _TRACE_MIGRATION_SET_INCOMING_CHANNEL_DSTATE = 0;
uint16_t _TRACE_VMSTATE_SUBSECTION_LOAD_BAD_DSTATE = 0;
uint16_t _TRACE_VMSTATE_SUBSECTION_LOAD_GOOD_DSTATE = 0;
uint16_t _TRACE_VMSTATE_LOAD_STATE_DSTATE = 0;
uint16_t _TRACE_VMSTATE_LOAD_STATE_END_DSTATE = 0;
uint16_t _TRACE_VMSTATE_LOAD_FIELD_ERROR_DSTATE = 0;
uint16_t _TRACE_MIGRATION_TLS_INCOMING_HANDSHAKE_START_DSTATE = 0;
uint16_t _TRACE_MIGRATION_TLS_INCOMING_HANDSHAKE_ERROR_DSTATE = 0;
uint16_t _TRACE_MIGRATION_TLS_INCOMING_HANDSHAKE_COMPLETE_DSTATE = 0;
uint16_t _TRACE_VMSTATE_SUBSECTION_LOAD_DSTATE = 0;
uint16_t _TRACE_VMSTATE_LOAD_STATE_FIELD_DSTATE = 0;
uint16_t _TRACE_PROCESS_INCOMING_MIGRATION_CO_END_DSTATE = 0;
uint16_t _TRACE_PROCESS_INCOMING_MIGRATION_CO_POSTCOPY_END_MAIN_DSTATE = 0;
uint16_t _TRACE_GET_QTAILQ_END_DSTATE = 0;
uint16_t _TRACE_GET_QTAILQ_DSTATE = 0;
uint16_t _TRACE_GET_GTREE_END_DSTATE = 0;
uint16_t _TRACE_GET_GTREE_DSTATE = 0;
uint16_t _TRACE_PUT_QTAILQ_DSTATE = 0;
uint16_t _TRACE_PUT_QTAILQ_END_DSTATE = 0;
uint16_t _TRACE_PUT_GTREE_DSTATE = 0;
uint16_t _TRACE_PUT_GTREE_END_DSTATE = 0;
uint16_t _TRACE_GET_QLIST_DSTATE = 0;
uint16_t _TRACE_GET_QLIST_END_DSTATE = 0;
uint16_t _TRACE_PUT_QLIST_DSTATE = 0;
uint16_t _TRACE_PUT_QLIST_END_DSTATE = 0;
uint16_t _TRACE_QEMU_LOADVM_STATE_POST_MAIN_DSTATE = 0;
uint16_t _TRACE_LOADVM_STATE_SETUP_DSTATE = 0;
uint16_t _TRACE_LOADVM_HANDLE_CMD_PACKAGED_MAIN_DSTATE = 0;
uint16_t _TRACE_POSTCOPY_RAM_LISTEN_THREAD_EXIT_DSTATE = 0;
uint16_t _TRACE_POSTCOPY_RAM_LISTEN_THREAD_START_DSTATE = 0;
uint16_t _TRACE_LOADVM_POSTCOPY_HANDLE_RESUME_DSTATE = 0;
uint16_t _TRACE_LOADVM_HANDLE_CMD_PACKAGED_RECEIVED_DSTATE = 0;
uint16_t _TRACE_QEMU_LOADVM_STATE_SECTION_PARTEND_DSTATE = 0;
uint16_t _TRACE_LOADVM_POSTCOPY_HANDLE_LISTEN_DSTATE = 0;
uint16_t _TRACE_LOADVM_HANDLE_CMD_PACKAGED_DSTATE = 0;
uint16_t _TRACE_LOADVM_STATE_SWITCHOVER_ACK_NEEDED_DSTATE = 0;
uint16_t _TRACE_LOADVM_POSTCOPY_HANDLE_RUN_DSTATE = 0;
uint16_t _TRACE_LOADVM_POSTCOPY_HANDLE_ADVISE_DSTATE = 0;
uint16_t _TRACE_LOADVM_PROCESS_COMMAND_DSTATE = 0;
uint16_t _TRACE_QEMU_LOADVM_STATE_SECTION_COMMAND_DSTATE = 0;
uint16_t _TRACE_VMSTATE_DOWNTIME_LOAD_DSTATE = 0;
uint16_t _TRACE_QEMU_LOADVM_STATE_SECTION_DSTATE = 0;
uint16_t _TRACE_POSTCOPY_PAUSE_INCOMING_DSTATE = 0;
uint16_t _TRACE_LOADVM_PROCESS_COMMAND_PING_DSTATE = 0;
uint16_t _TRACE_POSTCOPY_PAUSE_INCOMING_CONTINUED_DSTATE = 0;
uint16_t _TRACE_LOADVM_STATE_CLEANUP_DSTATE = 0;
uint16_t _TRACE_QEMU_LOADVM_STATE_SECTION_STARTFULL_DSTATE = 0;
uint16_t _TRACE_VMSTATE_LOAD_DSTATE = 0;
uint16_t _TRACE_LOADVM_HANDLE_RECV_BITMAP_DSTATE = 0;
uint16_t _TRACE_POSTCOPY_PAGE_REQ_SYNC_DSTATE = 0;
uint16_t _TRACE_LOADVM_POSTCOPY_RAM_HANDLE_DISCARD_END_DSTATE = 0;
uint16_t _TRACE_LOADVM_POSTCOPY_RAM_HANDLE_DISCARD_DSTATE = 0;
uint16_t _TRACE_LOADVM_POSTCOPY_RAM_HANDLE_DISCARD_HEADER_DSTATE = 0;
uint16_t _TRACE_MULTIFD_RECV_NEW_CHANNEL_DSTATE = 0;
uint16_t _TRACE_MULTIFD_RECV_THREAD_START_DSTATE = 0;
uint16_t _TRACE_MULTIFD_RECV_THREAD_END_DSTATE = 0;
uint16_t _TRACE_MULTIFD_RECV_TERMINATE_THREADS_DSTATE = 0;
uint16_t _TRACE_QIO_CHANNEL_FILE_NEW_PATH_DSTATE = 0;
uint16_t _TRACE_MIGRATION_RATE_LIMIT_PRE_DSTATE = 0;
uint16_t _TRACE_MULTIFD_RECV_UNFILL_DSTATE = 0;
uint16_t _TRACE_POSTCOPY_PREEMPT_NEW_CHANNEL_DSTATE = 0;
uint16_t _TRACE_MIGRATE_SEND_RP_MESSAGE_DSTATE = 0;
uint16_t _TRACE_MIGRATE_SEND_RP_RECV_BITMAP_DSTATE = 0;
uint16_t _TRACE_MIGRATION_RATE_LIMIT_POST_DSTATE = 0;
uint16_t _TRACE_JOB_STATE_TRANSITION_DSTATE = 0;
uint16_t _TRACE_MIGRATE_GLOBAL_STATE_POST_LOAD_DSTATE = 0;
uint16_t _TRACE_MIGRATE_GLOBAL_STATE_PRE_SAVE_DSTATE = 0;
uint16_t _TRACE_MIGRATION_FD_INCOMING_DSTATE = 0;
uint16_t _TRACE_QIO_CHANNEL_FILE_NEW_FD_DSTATE = 0;


/* Trace functions */
int __attribute__((weak)) trace_events_enabled_count(void)
{
    switch_log("STUB: trace_events_enabled_count called\n");
    return 0;
}

void __attribute__((weak)) trace_event_register_group(void *group)
{
    switch_log("STUB: trace_event_register_group called\n");
    (void)group;
}
void __attribute__((weak)) trace_event_set_state_dynamic(void *ev, bool state)
{
    switch_log("STUB: trace_event_set_state_dynamic called\n");
    (void)ev; (void)state;
}
